FROM node:18-slim as builder

WORKDIR /app

ARG STRAPI_TOKEN
ARG PUBLIC_API_DOMAIN
ARG PUBLIC_STRAPI_DOMAIN

ENV STRAPI_TOKEN=${STRAPI_TOKEN}
ENV PUBLIC_API_DOMAIN=${PUBLIC_API_DOMAIN}
ENV PUBLIC_STRAPI_DOMAIN=${PUBLIC_STRAPI_DOMAIN}

COPY package.json  ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install

COPY . .

RUN pnpm run build

FROM node:18-slim

WORKDIR /app

COPY package.json  ./
COPY --from=builder /app/build ./build

ARG STRAPI_TOKEN
ARG PUBLIC_API_DOMAIN
ARG PUBLIC_STRAPI_DOMAIN

RUN echo ${STRAPI_TOKEN}
RUN echo ${PUBLIC_API_DOMAIN}
RUN echo ${PUBLIC_STRAPI_DOMAIN}

ENV STRAPI_TOKEN=${STRAPI_TOKEN}
ENV PUBLIC_API_DOMAIN=${PUBLIC_API_DOMAIN}
ENV PUBLIC_STRAPI_DOMAIN=${PUBLIC_STRAPI_DOMAIN}

EXPOSE 8000
ENV PORT=8000

CMD ["node", "build/index.js"]
